"""Small performance refinements layered onto the native lifecycle manager."""

from __future__ import annotations

import asyncio
from typing import Any

from .models import NotificationRecord
from .native_manager import (
    LifecycleNotificationManager as NativeLifecycleNotificationManager,
)

DEFAULT_IGNORED_COALESCE_SECONDS = 5.0


class LifecycleNotificationManager(NativeLifecycleNotificationManager):
    """Coalesce repeated non-history ignored-state persistence."""

    ignored_coalesce_seconds = DEFAULT_IGNORED_COALESCE_SECONDS

    def _ignored_flush_tasks(self) -> dict[str, asyncio.Task[Any]]:
        tasks = getattr(self, "_ignored_persistence_tasks", None)
        if tasks is None:
            tasks = {}
            self._ignored_persistence_tasks = tasks
        return tasks

    def _ignored_flush_done(self, record_id: str, task: asyncio.Task[Any]) -> None:
        tasks = self._ignored_flush_tasks()
        if tasks.get(record_id) is task:
            tasks.pop(record_id, None)

    async def _flush_repeated_ignored(
        self,
        record_id: str,
        revision: int,
        reason: str,
    ) -> None:
        await asyncio.sleep(self.ignored_coalesce_seconds)
        async with self._lock(record_id):
            current = self.store.records.get(record_id)
            if (
                current is None
                or current.revision != revision
                or current.last_ignored_reason != reason
            ):
                return
            await self.store.async_save()
        self._broadcast("ignored", current, current.id)

    async def _async_persist_ignored(
        self, record: NotificationRecord, reason: str
    ) -> None:
        """Persist a changed ignore reason now and coalesce exact repeats.

        Cooldown, debounce, active-period, and active-occurrence rejects can be
        generated by noisy entities. The first/new reason is still durable and
        visible immediately. Repeated copies of the same reason are persisted at
        most once per short window, preserving the latest trigger snapshot without
        rewriting the complete Store document for every event.
        """
        previous_reason = record.last_ignored_reason
        record.last_ignored_reason = reason
        tasks = self._ignored_flush_tasks()

        if previous_reason != reason:
            if pending := tasks.pop(record.id, None):
                pending.cancel()
            await self.store.async_save()
            self._broadcast("ignored", record, record.id)
            return

        pending = tasks.get(record.id)
        if pending is not None and not pending.done():
            return

        task = self._schedule_task(
            self._flush_repeated_ignored(record.id, record.revision, reason)
        )
        if task is None:
            return
        tasks[record.id] = task
        task.add_done_callback(
            lambda completed, record_id=record.id: self._ignored_flush_done(
                record_id, completed
            )
        )
